In [24]:
import torch
from torch import nn
import numpy as np
from torch import Tensor
from torch import FloatTensor
from torch.autograd import Variable
from torch.nn.functional import relu

In [10]:
a = Variable(Tensor(np.array([1, 3, 4])))

In [12]:
a + a

Variable containing:
 2
 6
 8
[torch.FloatTensor of size 3]

In [27]:
class VN(nn.Module):
    
    def __init__(self):
        super(VN, self).__init__()
        self.lin1 = nn.Linear(3, 100)
        self.lin2 = nn.Linear(100, 2)
    
    def forward(self, x):
        return relu(self.lin2(relu(self.lin1(x))))
        

In [20]:
vn = VN()

In [28]:
print(vn)

VN(
  (lin1): Linear(in_features=3, out_features=100)
  (lin2): Linear(in_features=100, out_features=2)
)


In [36]:
output = vn(Variable(FloatTensor(np.array([1, 3, 2]))))

In [72]:
target = torch.max(vn(Variable(FloatTensor(np.array([[1, 3, 2], [1, 2, 5]])))), 0)[0] + Variable(Tensor(np.array([1, 5])))

In [80]:
test = vn(Variable(FloatTensor(np.array([[1, 3, 2], [1, 2, 5]]))))
print(test)
predicted = test[range(test.size()[0]), [0, 1]]

Variable containing:
 0.0127  0.0000
 0.0000  0.9330
[torch.FloatTensor of size 2x2]



In [84]:
torch.sum((predicted - target)**2)

Variable containing:
 26
[torch.FloatTensor of size 1]

In [185]:
a = [0, 0, 0, 0]

In [186]:
a[3] = np.array([1, 2])

In [187]:
a

[0, 0, 0, array([1, 2])]

In [40]:
import gym
env = gym.make('CartPole-v0')
env.reset()

[2017-11-18 19:24:23,109] Making new env: CartPole-v0


array([-0.04222198, -0.0266509 ,  0.00609133,  0.03338946])

In [51]:
env.step(1)

(array([ 0.12822217,  1.92890912, -0.25578164, -3.0674591 ]), 1.0, True, {})

In [49]:
env.observation_space.higha

env.observation_space.low

(env - env.observation_space.low)/(env.observation_space.high - env.observation_space.high)

AttributeError: 'Box' object has no attribute 'higha'

In [172]:
env.action_space.shape[0]

2

In [173]:
_, idx = output.max(0)

In [42]:
idx

Variable containing:
 0
[torch.LongTensor of size 1]

In [54]:
Tensor(4).uniform_(0, 1)


 0.0458
 0.7057
 0.0206
 0.0932
[torch.FloatTensor of size 4]

In [58]:
np.random.rand()

0.2319741492792422

In [55]:
torch.rand(5)


 0.0666
 0.9033
 0.6206
 0.0213
 0.4470
[torch.FloatTensor of size 5]

In [110]:
t = np.array([np.random.randint(5)])

In [113]:
t

array([0])

In [114]:
a = FloatTensor([5])

In [115]:
a.numpy()

array([ 5.], dtype=float32)

In [116]:
from torch import random

In [123]:
import random
random.sample([5, 6,6, 3], 2)

[6, 6]

In [124]:
a


 5
[torch.FloatTensor of size 1]

In [125]:
b = Variable(a)

In [126]:

b

Variable containing:
 5
[torch.FloatTensor of size 1]

In [134]:
int(b)

5

In [143]:
from torch import LongTensor
a = torch.stack([FloatTensor([1, 2, 3]), FloatTensor([1, 5, 5])]).long()

In [150]:
a


 1  2  3
 1  5  5
[torch.LongTensor of size 2x3]

In [162]:
a.matmul(a.t())


 14  26
 26  51
[torch.LongTensor of size 2x2]

In [161]:

a.numpy().dot(a.numpy().T)

array([[14, 26],
       [26, 51]])

# Experiments for the memory

In [169]:
mem = FloatTensor(5)

In [170]:
mem


 0.0000e+00
-8.5899e+09
-1.0073e-26
 8.5920e+09
 2.3492e-22
[torch.FloatTensor of size 5]

In [168]:
torch.stack([mem, FloatTensor([5, 6, 6])])

RuntimeError: invalid argument 2: cannot unsqueeze empty tensor at /Users/william/Documents/pytorch/torch/lib/TH/generic/THTensor.c:601

# Experiments for the knn

In [139]:
from torch import FloatTensor
import numpy as np
import torch
s_mem  = FloatTensor(np.random.randn(100, 2))

In [140]:
v_mem = [FloatTensor(np.random.randn(100, 1)) for _ in range(4)]

In [143]:
state = FloatTensor([1, 3])[None]

In [74]:
import torch.nn.functional as F

In [75]:
[None, None, None]

[None, None, None]

In [360]:
a = torch.zeros(5, 1)
b = torch.zeros(5, 2)



In [296]:
a[3]= 2

In [361]:
a[3] = 1

In [309]:
from torch import ByteTensor
a.byte()


 0
 0
 0
 1
 0
[torch.ByteTensor of size 5x1]

In [353]:
a = np.zeros((5, 1))
b = np.zeros((5, 2))
a[1] = 1

In [398]:
torch.nonzero(a == 1, 1)

TypeError: Type int doesn't implement stateless methods

In [401]:
%pdb
b[(a==1)]

Automatic pdb calling has been turned ON


RuntimeError: inconsistent tensor size, expected src [5 x 2] and mask [5 x 1] to have the same number of elements, but got 10 and 5 elements respectively at /Users/william/Documents/pytorch/torch/lib/TH/generic/THTensorMath.c:197

> <ipython-input-401-9806a2646aee>(2)<module>()
      1 get_ipython().magic('pdb')
----> 2 b[(a==1)]

ipdb> up
*** Oldest frame
--KeyboardInterrupt--
--KeyboardInterrupt--
ipdb> exit


In [399]:
b[(a==1).nonzero()[:, 0]]


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [392]:
(a == 1).nonzero()


 0  0
 3  0
[torch.LongTensor of size 2x2]

In [354]:
b[(a == 1).ravel()]

array([[ 0.,  0.]])

In [362]:
(a == 1).squeeze(1)


 0
 0
 0
 1
 0
[torch.ByteTensor of size 5]

In [356]:
ByteTensor(5)


 0
 0
 0
 0
 0
[torch.ByteTensor of size 5]

In [357]:
b[ByteTensor(5)]

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [359]:
b

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [368]:
b


 0  0
 0  0
 0  0
 0  0
 0  0
[torch.FloatTensor of size 5x2]

In [372]:
a[0] = 1

In [384]:
b[[0, 1, 0, 1, 1] , :]


 0  0
 0  0
 0  0
 0  0
 0  0
[torch.FloatTensor of size 5x2]

In [374]:
b[(a == 1).expand_as(b)]


 0
 0
 0
 0
[torch.FloatTensor of size 4]

In [320]:
b[a == 1]

IndexError: boolean index did not match indexed array along dimension 1; dimension is 2 but corresponding boolean dimension is 1

In [287]:
a[0, :] = 1

In [289]:
env.step(0)

[2017-11-18 23:09:02,630] You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


(array([ 0.16680036,  1.73587912, -0.31713082, -2.86171669]), 0.0, True, {})

In [288]:
a


 1
 0
 0
 0
 0
[torch.FloatTensor of size 5x1]

In [133]:
F.cosine_similarity(FloatTensor([[1, 0, 1], [0, 1, 0]])[:, None], FloatTensor([[1, 0, 1], [0, 1, 0], [1, 1, 1], [1, 0, 0]])[None], 2)


 1.0000  0.0000  0.8165  0.7071
 0.0000  1.0000  0.5774  0.0000
[torch.FloatTensor of size 2x4]

In [270]:
i = F.cosine_similarity(state[:, None], s_mem[None], 2).topk(5)[1]

In [271]:
v_mem[0][i, :].mean(-2)


-0.4269
[torch.FloatTensor of size 1]

In [223]:
v_mem[0][i]

IndexError: Indexing a Tensor with a torch.LongTensor triggers index_select semantics, and thus we expect a vector, but the indexing Tensor passed has 2 dimensions

In [232]:
a = FloatTensor(np.array([[1, 2, 3], [1, 2, 4]]))

In [248]:
from torch import LongTensor
ind = LongTensor(np.array([[1, 0], [0, 1]]))
ind1 = LongTensor([1, 2])
indnp = np.array([[1, 0], [0, 1]])

In [255]:
a[ind, :]


(0 ,.,.) = 
  1  2  4
  1  2  3

(1 ,.,.) = 
  1  2  3
  1  2  4
[torch.FloatTensor of size 2x2x3]

In [242]:
help(F.cosine_similarity)

Help on function cosine_similarity in module torch.nn.functional:

cosine_similarity(x1, x2, dim=1, eps=1e-08)
    Returns cosine similarity between x1 and x2, computed along dim.
    
    .. math ::
        \text{similarity} = \dfrac{x_1 \cdot x_2}{\max(\Vert x_1 \Vert _2 \cdot \Vert x_2 \Vert _2, \epsilon)}
    
    Args:
        x1 (Variable): First input.
        x2 (Variable): Second input (of size matching x1).
        dim (int, optional): Dimension of vectors. Default: 1
        eps (float, optional): Small value to avoid division by zero.
            Default: 1e-8
    
    Shape:
        - Input: :math:`(\ast_1, D, \ast_2)` where D is at position `dim`.
        - Output: :math:`(\ast_1, \ast_2)` where 1 is at position `dim`.
    
    Example::
    
        >>> input1 = autograd.Variable(torch.randn(100, 128))
        >>> input2 = autograd.Variable(torch.randn(100, 128))
        >>> output = F.cosine_similarity(input1, input2)
        >>> print(output)



In [200]:
state


 1  3
[torch.FloatTensor of size 1x2]

In [199]:
eps = 1e-8
x1 = state[:, None]
x2 = s_mem[None]
w12 = torch.sum(x1 * x2, 2)
w1 = torch.norm(x1, 2, 2)
w2 = torch.norm(x2, 2, 2)
(w12 / (w1 * w2).clamp(min=eps)).squeeze()


-0.7635
 0.3370
 0.9564
 0.9447
 0.4093
-0.9466
-0.6213
-0.3125
-0.4453
 0.1094
 0.8324
 0.2135
 0.9974
 0.8643
-0.5336
-0.5940
-0.8442
-0.9098
 0.5693
 0.6833
-0.3787
-0.7390
 0.5254
 0.6522
-0.4946
 0.8333
-0.3022
 0.6180
-0.2257
 0.6573
 0.5824
 0.2010
-0.1665
 0.9996
-0.8352
 0.0694
-0.3886
-0.3297
 0.3329
-0.4729
 0.2248
-0.5527
-0.2149
-0.6121
 0.6488
 0.9989
-0.1970
-0.3846
-0.5719
 0.0165
 0.9767
-0.7339
-0.9555
 0.1796
-0.7483
-0.8959
-0.9901
-0.9218
-0.0943
-0.1332
-0.0946
 0.1726
-0.0603
-0.8135
-0.8129
-0.1310
-0.9899
 0.7133
-0.8279
-0.9662
 0.6036
 0.9859
-0.4437
 0.7236
 0.7821
-0.8103
-0.0282
-0.8379
 0.9657
-0.6368
-0.7054
-0.7990
-0.8578
-0.0102
 0.9526
 0.9936
-0.7754
-0.0613
-0.6813
-0.8872
-0.5721
-0.0233
 0.6863
-0.9963
 0.3231
-0.9547
 0.9783
-0.8426
 0.6397
-0.8633
[torch.FloatTensor of size 100]

In [176]:
a.float().mean(0)


 49.2000
[torch.FloatTensor of size 1]

In [96]:
F.cosine_similarity(states[:, None], s_mem[0])

RuntimeError: inconsistent tensor size, expected r_ [2 x 2], t [2 x 2] and src [100] to have the same number of elements, but got 4, 4 and 100 elements respectively at /Users/william/Documents/pytorch/torch/lib/TH/generic/THTensorMath.c:1023

In [76]:
def _Q(s, a):
    indices = F.cosine_similarity(s[None], s_mem[a]).topk(5)[1]
    value = torch.mean(v_mem[a][indices])
    return value

In [79]:
states = torch.stack([state, state])

In [87]:
_Q(states, 0)

RuntimeError: inconsistent tensor size, expected r_ [1 x 2 x 2], t [1 x 2 x 2] and src [100 x 2] to have the same number of elements, but got 4, 4 and 200 elements respectively at /Users/william/Documents/pytorch/torch/lib/TH/generic/THTensorMath.c:1023

In [63]:
state

NameError: name 'state' is not defined

In [248]:
max(_Q(state, a) for a in range(4))

0.6171616673469543

In [249]:
torch.zeros(state.size())


 0
 0
[torch.FloatTensor of size 2]

In [250]:
torch.nan

AttributeError: module 'torch' has no attribute 'nan'

In [260]:
from torch import ByteTensor
a = ByteTensor(5)
b = torch.zeros(5)

In [261]:
a[1] = 1
a[3] = 1

In [262]:
b[a]


 0
 0
[torch.FloatTensor of size 2]

In [197]:
help(F.cosine_similarity)

Help on function cosine_similarity in module torch.nn.functional:

cosine_similarity(x1, x2, dim=1, eps=1e-08)
    Returns cosine similarity between x1 and x2, computed along dim.
    
    .. math ::
        \text{similarity} = \dfrac{x_1 \cdot x_2}{\max(\Vert x_1 \Vert _2 \cdot \Vert x_2 \Vert _2, \epsilon)}
    
    Args:
        x1 (Variable): First input.
        x2 (Variable): Second input (of size matching x1).
        dim (int, optional): Dimension of vectors. Default: 1
        eps (float, optional): Small value to avoid division by zero.
            Default: 1e-8
    
    Shape:
        - Input: :math:`(\ast_1, D, \ast_2)` where D is at position `dim`.
        - Output: :math:`(\ast_1, \ast_2)` where 1 is at position `dim`.
    
    Example::
    
        >>> input1 = autograd.Variable(torch.randn(100, 128))
        >>> input2 = autograd.Variable(torch.randn(100, 128))
        >>> output = F.cosine_similarity(input1, input2)
        >>> print(output)



In [196]:
help(torch.nn.CosineEmbeddingLoss)

Help on class CosineEmbeddingLoss in module torch.nn.modules.loss:

class CosineEmbeddingLoss(torch.nn.modules.module.Module)
 |  Creates a criterion that measures the loss given  an input tensors
 |  x1, x2 and a `Tensor` label `y` with values 1 or -1.
 |  This is used for measuring whether two inputs are similar or dissimilar,
 |  using the cosine distance, and is typically used for learning nonlinear
 |  embeddings or semi-supervised learning.
 |  
 |  `margin` should be a number from `-1` to `1`, `0` to `0.5` is suggested.
 |  If `margin` is missing, the default value is `0`.
 |  
 |  The loss function for each sample is::
 |  
 |                   { 1 - cos(x1, x2),              if y ==  1
 |      loss(x, y) = {
 |                   { max(0, cos(x1, x2) - margin), if y == -1
 |  
 |  If the internal variable `size_average` is equal to `True`,
 |  the loss function averages the loss over the batch samples;
 |  if `size_average` is `False`, then the loss function sums over the
 |  b